### ISSUE TITLE
HomePage

### ISSUE THREAD

**Issue by amanpreet09** [teamprojectsorg/FitnessApp#4]
remove graph from home add progress tile and help tile

**Comment by kashyapjain** [comment]
Graph should be showing the data of average male vs female alcohol intake 
Use revant data attached below

[aihw-phe-221-impacts_AUGUST-2022.xlsx](https://github.com/teamprojectsorg/FitnessApp/files/9475259/aihw-phe-221-impacts_AUGUST-2022.xlsx)
[age.xlsx](https://github.com/teamprojectsorg/FitnessApp/files/9475261/age.xlsx)
[TABLE 7 Alcohol by age and sex.xlsx](https://github.com/teamprojectsorg/FitnessApp/files/9475263/TABLE.7.Alcohol.by.age.and.sex.xlsx)
